spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lewicdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root12#$
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  typeAliasesPackage: com.lewic.ssmdemo.model
  mapperLocations: classpath:mapper/*.xml

server:
  port: 8082
